export default [
    {
      id: 1,
      brand: "Tokyo Talkies",
      title: "Washed denim Jacket",
      offerPrice: 1034,
      mrp: 3099,
      url: "../Images/gallery-02.jpg",
      wishlist: false,
    },
    {
      id: 2,
        brand: "Tokyo Talkies",
      newSeason:false,
      title: "Cropped Trucker Jacket",
      offerPrice: 1034,
      mrp: 3099,
      url: "../Images/gallery-06.jpg",
      wishlist: true,
    },
    {
      id: 3,
      brand: "Tokyo Talkies",
      title: "Washed denim Jacket",
      offerPrice: 1034,
      mrp: 3099,
      url: "../Images/gallery-06.jpg",
      wishlist: false,
    },
    {
      id: 4,
      brand: "Tokyo Talkies",
      title: "Cropped Trucker Jacket",
      offerPrice: 1034,
      mrp: 3099,
      url: "../Images/gallery-05.jpg",
      wishlist: false,
    },
    {
      id: 5,
      title: "Cropped Trucker Jacket",
      offerPrice: 1034,
      mrp: 3099,
      url: "../Images/gallery-02.jpg",
      wishlist: false,
    },
    {
      id: 6,
      brand: "Tokyo Talkies",
      title: "Cropped Trucker Jacket",
      offerPrice: 1034,
      mrp: 3099,
      url: "../Images/gallery-06.jpg",
      wishlist: false,
    },
    {
      id: 7,
      brand: "Tokyo Talkies",
      title: "Cropped Trucker Jacket",
      offerPrice: 1034,
      mrp: 3099,
      url: "../Images/gallery-05.jpg",
      wishlist: false,
    },
  ];